### ISSUE TITLE
지난행사보기 버튼을 눌러도 원래 티저홈페이지가 뜹니다. 

### ISSUE THREAD

**Issue by bluejayA** [openstack-kr/event.openstack.or.kr#6]
링크는 2018로 걸려있는데, 누르면 가는듯하다가 원래 2019 티저홈페이지로 돌아옴.

**Comment by bluejayA** [comment]
페이지 띄울때 target="_blank" 붙여서 새 창으로 띄우면 해결되나요?

**Comment by ujuc** [comment]
캐쉬 지워보시겠어요?

mac기준 chrom에서는 `cmd` + `shift` + `r` 하시면 캐시 강제 고침으로 날라갑니다.
